# Generated by Django 3.2.5 on 2021-08-30 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
