# Generated by Django 3.2.5 on 2021-09-18 05:38

import datetime
from django.db import migrations, models
import shop.models.product


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20210918_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 9, 18, 11, 8, 26, 195589)),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(max_length=19, verbose_name=shop.models.product.Product),
        ),
    ]
